# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

count_zeroes <- function(x) {
    .Call(`_milou_count_zeroes`, x)
}

random_split_double <- function(x) {
    .Call(`_milou_random_split_double`, x)
}

random_split_int <- function(x) {
    .Call(`_milou_random_split_int`, x)
}

rcpp_hello_world <- function() {
    .Call(`_milou_rcpp_hello_world`)
}

splitR_double <- function(x, pivot) {
    .Call(`_milou_splitR_double`, x, pivot)
}

splitR_int <- function(x, pivot) {
    .Call(`_milou_splitR_int`, x, pivot)
}

